Add html pages to the project
Algor-Fernand/git-exercise pull request #1
Opened 2023-07-11 10:10 UTC by Algor-Fernand

Create the html pages for the home, about and services pages.

#Bundle2  Exercise 1

PS C:\Users\DOLPHIX ELECTRONICS\git-exercise> git init
Initialized empty Git repository in C:/Users/DOLPHIX ELECTRONICS/git-exercise/.git/
PS C:\Users\DOLPHIX ELECTRONICS\git-exercise> git status                   
On branch main

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   index.html

Untracked files:

PS C:\Users\DOLPHIX ELECTRONICS\git-exercise> git add .
[main (root-commit) b409ad9] initial commit
 2 files changed, 3 insertions(+)
 create mode 100644 index.html
 create mode 100644 readme.md
PS C:\Users\DOLPHIX ELECTRONICS\git-exercise> git remote add origin https://github.com/Algor-Fernand/git-exercise.git
PS C:\Users\DOLPHIX ELECTRONICS\git-exercise> git status
On branch main
PS C:\Users\DOLPHIX ELECTRONICS\git-exercise> git push origin
fatal: The current branch main has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin main

To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'git help config'.

Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/Algor-Fernand/git-exercise.git
 * [new branch]      main -> main
branch 'main' set up to track 'origin/main'.
PS C:\Users\DOLPHIX ELECTRONICS\git-exercise> git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
PS C:\Users\DOLPHIX ELECTRONICS\git-exercise> git checkout -b dev
Switched to a new branch 'dev'
PS C:\Users\DOLPHIX ELECTRONICS\git-exercise>  

//git bash 

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git status
On branch dev
nothing to commit, working tree clean

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git checkout -b test
Switched to a new branch 'test'

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (test)
$ git status
On branch test
nothing to commit, working tree clean

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (test)
$ git checkout dev
Switched to branch 'dev'

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git branch -D test
Deleted branch test (was b409ad9).

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git status
On branch dev
nothing to commit, working tree clean

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git push origin --delete test
error: unable to delete 'test': remote ref does not exist
error: failed to push some refs to 'https://github.com/Algor-Fernand/git-exercise.git'

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git checkout -b test
Switched to a new branch 'test'

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (test)
$ git status
On branch test
nothing to commit, working tree clean

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (test)
$ git push origin
fatal: The current branch test has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin test

To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'git help config'.

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (test)
$     git push --set-upstream origin test
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: 
remote: Create a pull request for 'test' on GitHub by visiting:
remote:      https://github.com/Algor-Fernand/git-exercise/pull/new/test
remote:
To https://github.com/Algor-Fernand/git-exercise.git
 * [new branch]      test -> test
branch 'test' set up to track 'origin/test'.

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (test)
$ git checkout dev
Switched to branch 'dev'

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$     git push --set-upstream origin dev
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: 
remote: Create a pull request for 'dev' on GitHub by visiting:
remote:      https://github.com/Algor-Fernand/git-exercise/pull/new/dev
remote:
To https://github.com/Algor-Fernand/git-exercise.git
 * [new branch]      dev -> dev
branch 'dev' set up to track 'origin/dev'.

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git checkout -D test
error: unknown switch `D'
usage: git checkout [<options>] <branch>
   or: git checkout [<options>] [<branch>] -- <file>...

    -b <branch>           create and checkout a new branch
    -B <branch>           create/reset and checkout a branch
    -l                    create reflog for new branch
    --guess               second guess 'git checkout <no-such-branch>' (default)
    --overlay             use overlay mode (default)
    -q, --quiet           suppress progress reporting
    --recurse-submodules[=<checkout>]
                          control recursive updating of submodules
    --progress            force progress reporting
    -m, --merge           perform a 3-way merge with the new branch
    --conflict <style>    conflict style (merge, diff3, or zdiff3)
    -d, --detach          detach HEAD at named commit
    -t, --track[=(direct|inherit)]
                          set branch tracking configuration
    -f, --force           force checkout (throw away local modifications)
    --orphan <new-branch>
                          new unparented branch
    --overwrite-ignore    update ignored files (default)
    --ignore-other-worktrees
                          do not check if another worktree is holding the given ref
    -2, --ours            checkout our version for unmerged files
    -3, --theirs          checkout their version for unmerged files
    -p, --patch           select hunks interactively
    --ignore-skip-worktree-bits
                          do not limit pathspecs to sparse entries only
    --pathspec-from-file <file>
                          read pathspec from file
    --pathspec-file-nul   with --pathspec-from-file, pathspec elements are separated with NUL character   

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git branch -D test
Deleted branch test (was b409ad9).

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git push origin --delete test
To https://github.com/Algor-Fernand/git-exercise.git
 - [deleted]         test

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$     git push --set-upstream origin dev
Everything up-to-date
branch 'dev' set up to track 'origin/dev'.

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git status
On branch dev
Your branch is up to date with 'origin/dev'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)        
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    index.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        home.html

no changes added to commit (use "git add" and/or "git commit -a")

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git add home.html

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git add .

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git status
On branch dev
Your branch is up to date with 'origin/dev'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        renamed:    index.html -> home.html

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git add .

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git add .$
fatal: pathspec '.$' did not match any files

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ git add .

DOLPHIX ELECTRONICS@DESKTOP-TJ49EDU MINGW64 ~/git-exercise (dev)
$ [...]

2023-07-11 11:10 UTC, kaitcham approved these changes
Hi, @Algor-Fernand 👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit:

2023-07-11 16:55 UTC, Yvad60 requested changes
Hi @Algor-Fernand. Good job on the changes, I took a peek at your changes and the bits I saw looked good. Instead of putting your terminal logs in the PR description I would recommend creating a `README.md`  and paste your terminal logs there. For this check the video about how to submit exercises in the video playlist shared with you

With the current implementation after merging the current PR, you would loose all your changes because they would be closed with the PR itself

2023-07-13 10:11 UTC, Yvad60 approved these changes
I left a comment about how to use code blocks properly but everything else looks good to me. Good job

2023-07-13 10:11 UTC, Yvad60 commented on readme.md
> +Switched to branch 'ft/bundle-2'
If you want to add a code block you use 3 backticks like ``` you can find backticks on the key above the tab key

2023-07-13 12:38 UTC, merged